# Permalinks
permalink:           pretty

# Setup
title:               Abdul Rahman
tagline:             Computer Engineer from Singapore
url:                 www.arshanapps.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Abdul Rahman
  url:               www.arshanapps.com
  email:             arsh.abdulrahman@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/arshrahman/
google_analytics:    UA-3363703-15
twitter:             arshanrahman
github:              arshrahman
dribbble:            jamigibbs

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
